### ISSUE TITLE
qmpi: failed to build in mpich-4.0

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#5829]
From discuss mailinglist:

> [quote]
Hi Mpich team,

I see the following issue with the latest 4.0 release of MPICH while adding QMPI support at configure time?

make[2]: Entering directory `/scratch1/05231/aruhela/libs/mpich/tar-mpich-4.0'
  CC       src/binding/c/attr/lib_libmpi_la-attr_delete.lo
src/binding/c/attr/attr_delete.c(63): error: attributes are not permitted in a function definition
  int QMPI_Attr_delete(QMPI_Context context, int tool_id, MPI_Comm comm, int keyval) MPICH_API_PUBLIC
                                                                                                                                                                 ^

compilation aborted for src/binding/c/attr/attr_delete.c (code 2)
make[2]: *** [src/binding/c/attr/lib_libmpi_la-attr_delete.lo] Error 1

Any suggestions to resolve the build error?

Amit Ruhela, Ph.D. 
HPC Software Tools Group 
Texas Advanced Computing Center 
The University of Texas at Austin

**Comment by raffenet** [comment]
The fix for this is included in MPICH 4.0.1 https://github.com/pmodels/mpich/releases/tag/v4.0.1.
