### PR TITLE
Fix MPL/atomic issues

### PR DESCRIPTION
**Pull request by shintaro-iwasaki**
## Pull Request Description

This PR fixes some issues in MPL/atomic which is introduced by #3906.

The first commit is to remove warnings with `--enable-strict` (e.g., `-Wpedantic` in GCC). Previously typedef is defined in both `mpl_atomic.h` and `mpl_atomic_xxx.h`, so this PR removes the second typedef.

The second commit is moving `#include "mpl_atomic.h"` outside the ifdef block in order to make `MPL_HAVE_PTHREAD_H` visible.

## Expected Performance Changes

None.

## Known Issues

None.

## Author Checklist
* [ ] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [ ] Passes tests (included warning check)
* [ ] Confirm whitespace/style checkers are happy (or has a good reason for being bad)
* [ ] Commits are self-contained and do not do two things at once
* [ ] Remove xfail from the test suite when fixing a test
* [ ] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [ ] Add comments such that someone without knowledge of the code could understand
* [ ] Add Devel Docs in the `doc/` directory for any new code design

### CODE REVIEW

**Comment by shintaro-iwasaki** [comment]
The first commit shows the following warning:
```
In file included from src/bt/mpl_bt.c:7:
In file included from ./include/mpl.h:15:
In file included from ./include/mpl_atomic.h:94:
./include/mpl_atomic_gcc_atomic.h:78:1: warning: redefinition of typedef 'MPL_atomic_int_t' is a C11 feature [-Wtypedef-redefinition]
MPL_ATOMIC_DECL_FUNC_VAL(int, int)
^
./include/mpl_atomic_gcc_atomic.h:71:9: note: expanded from macro 'MPL_ATOMIC_DECL_FUNC_VAL'
        MPL_ATOMIC_DECL_FUNC_COMMON(TYPE, NAME) \
        ^
./include/mpl_atomic_gcc_atomic.h:24:3: note: expanded from macro 'MPL_ATOMIC_DECL_FUNC_COMMON'
} MPL_atomic_ ## NAME ## _t;                                                   \
  ^
<scratch space>:118:1: note: expanded from here
MPL_atomic_int_t
^
./include/mpl_atomic.h:13:33: note: previous definition is here
typedef struct MPL_atomic_int_t MPL_atomic_int_t;
```
It can be reproduced by the following code:
```
// in mpl_atomic.h
typedef struct atomic_t atomic_t;
// The declaration above is necessary for the forward declaration in mpl_atomic.h:
int func(atomic_t *x);

// in mpl_atomic_xxx.h
typedef struct atomic_t {
  int val;
} atomic_t;
```
Solved by removing typedef:
```
// in mpl_atomic_xxx.h
struct atomic_t {
  int val;
};
```
I'd like to thank @raffenet for reporting this issue!

**Comment by raffenet** [comment]
My understanding of the warning is that typedef redefinition is perfectly fine C11 code. In this case, the compiler does not default to C11 and thus throws a warning. Fix looks fine to me, but we should update the commit message for clarity.

**Comment by hzhou** [comment]
test:mpich/warnings

**Comment by hzhou** [comment]
test:mpich/warnings

**Comment by hzhou** [comment]
test:mpich/warnings

**Comment by hzhou** [comment]
test:mpich/warnings

**Comment by hzhou** [comment]
@gcongiu maybe you could take look at these warnings?
