### ISSUE TITLE
mpich-3.0.4 mpiexec breaks on freebsd

### ISSUE THREAD

**Issue by mpichbot** [pmodels/mpich#1820]
**Originally by _balay_ on 2013-04-26 16:11:50 -0500**

---

mpich-3.0.4 mpiexec breaks on freebsd - whereas an identical build with mpich-3.0.4 works.

```
[balay@wii ~/petsc.clone-3/src/ksp/ksp/examples/tutorials]$ ./ex2
Norm of error 0.000156044 iterations 6
[balay@wii ~/petsc.clone-3/src/ksp/ksp/examples/tutorials]$ ~/petsc.clone-3/arch-freebsd-cxx-cmplx-pkgs-dbg/bin/mpiexec -n 1 ./ex2
Norm of error 0.000156044 iterations 6
[balay@wii ~/petsc.clone-3/src/ksp/ksp/examples/tutorials]$ ~/petsc.clone-3/arch-freebsd-cxx-cmplx-pkgs-dbg/bin/mpiexec -n 2 ./ex2
[proxy:0:0@wii] stdoe_cb (./pm/pmiserv/pmip_cb.c:51): assert (i < HYD_pmcd_pmip.local.proxy_process_count) failed
[proxy:0:0@wii] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[proxy:0:0@wii] main (./pm/pmiserv/pmip.c:206): demux engine error waiting for event
[mpiexec@wii] control_cb (./pm/pmiserv/pmiserv_cb.c:202): assert (!closed) failed
[mpiexec@wii] HYDT_dmxu_poll_wait_for_event (./tools/demux/demux_poll.c:77): callback returned error status
[mpiexec@wii] HYD_pmci_wait_for_completion (./pm/pmiserv/pmiserv_pmci.c:197): error waiting for event
[mpiexec@wii] main (./ui/mpich/mpiexec.c:331): process manager error waiting for completion
[balay@wii ~/petsc.clone-3/src/ksp/ksp/examples/tutorials]$ 
```
