### ISSUE TITLE
mpich-4.0b1 build error in 32bit mode..

### ISSUE THREAD

**Issue by balay** [pmodels/mpich#5688]
Attempting a 32bit build on Fedora 35 with `gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)`

```
../configure --prefix=$HOME/soft/mpich-4.0b1-32  CC=gcc CXX=g++ FC=gfortran F77=gfortran CFLAGS=-m32 CXXFLAGS=-m32 FCFLAGS='-m32 -fallow-argument-mismatch' FFLAGS='-m32 -fallow-argument-mismatch' --enable
-shared --with-device=ch3:sock --with-pm=hydra --enable-fast=no --enable-error-messages=all --enable-g
```
And get:
```
/usr/bin/ld: i386:x86-64 architecture of input file `/home/glci/soft/build/mpich-4.0b1/objdir/modules/hwloc/hwloc/.libs/libhwloc_embedded.a(topology.o)' is incompatible with i386 output
```
CFLAGS isn't getting passed down to hwloc?

[config.log](https://github.com/pmodels/mpich/files/7572805/config.log)
[make.log](https://github.com/pmodels/mpich/files/7572806/make.log)

**Comment by balay** [comment]
Switching to the following gets the build going.
```
../configure --prefix=$HOME/soft/mpich-4.0b1-32  CC='gcc -m32'  CXX='g++ -m32' FC='gfortran -m32' F77='gfortran -m32' FCFLAGS='-fallow-argument-mismatch' FFLAGS='-fallow-argument-mismatch' --enable-shared
 --with-device=ch3:sock --with-pm=hydra --enable-fast=no --enable-error-messages=all --enable-g
```
But then:
```
[glci@pj03 f77]$ /home/glci/soft/mpich-4.0b1-32/bin/mpif90  fpi.f
/usr/bin/ld: /home/glci/soft/mpich-4.0b1-32/lib/libmpifort.so: undefined reference to `PMPI_Delete_error_code'
/usr/bin/ld: /home/glci/soft/mpich-4.0b1-32/lib/libmpifort.so: undefined reference to `PMPI_Delete_error_string'
/usr/bin/ld: /home/glci/soft/mpich-4.0b1-32/lib/libmpifort.so: undefined reference to `PMPI_Delete_error_class'
collect2: error: ld returned 1 exit status
```

**Comment by hzhou** [comment]
> CFLAGS isn't getting passed down to hwloc?

Indeed. Our negligence. Fix coming up. Now let me check https://github.com/pmodels/mpich/issues/5688#issuecomment-974468662

**Comment by hzhou** [comment]
> [glci@pj03 f77]$ /home/glci/soft/mpich-4.0b1-32/bin/mpif90  fpi.f
> /usr/bin/ld: /home/glci/soft/mpich-4.0b1-32/lib/libmpifort.so: undefined reference to `PMPI_Delete_error_code'
> /usr/bin/ld: /home/glci/soft/mpich-4.0b1-32/lib/libmpifort.so: undefined reference to `PMPI_Delete_error_string'
> /usr/bin/ld: /home/glci/soft/mpich-4.0b1-32/lib/libmpifort.so: undefined reference to `PMPI_Delete_error_class'
> collect2: error: ld returned 1 exit status

I am not reproducing this error. @balay Do you encounter similar error with 64-bit build?

**Comment by balay** [comment]
Hm - [I don't have my prior builds] - so did a rebuild - and can't reproduce this [with either 32bit or 64bit]. So don't know what went wrong with my previous build.

And I don't see `PMPI_Delete_error_code` type symbols - but see `PMPIX_**`..

```
[glci@pj03 f77]$ nm -AoD /home/glci/soft/mpich32-4.0b1/lib/*.so |grep Delete_error_code
/home/glci/soft/mpich32-4.0b1/lib/libfmpich.so:         U PMPIX_Delete_error_code
/home/glci/soft/mpich32-4.0b1/lib/libmpichf90.so:         U PMPIX_Delete_error_code
/home/glci/soft/mpich32-4.0b1/lib/libmpich.so:000e7109 W MPIX_Delete_error_code
/home/glci/soft/mpich32-4.0b1/lib/libmpich.so:000e7109 T PMPIX_Delete_error_code
/home/glci/soft/mpich32-4.0b1/lib/libmpifort.so:         U PMPIX_Delete_error_code
/home/glci/soft/mpich32-4.0b1/lib/libmpi.so:000e7109 W MPIX_Delete_error_code
/home/glci/soft/mpich32-4.0b1/lib/libmpi.so:000e7109 T PMPIX_Delete_error_code
/home/glci/soft/mpich32-4.0b1/lib/libmpl.so:000e7109 W MPIX_Delete_error_code
/home/glci/soft/mpich32-4.0b1/lib/libmpl.so:000e7109 T PMPIX_Delete_error_code
/home/glci/soft/mpich32-4.0b1/lib/libopa.so:000e7109 W MPIX_Delete_error_code
/home/glci/soft/mpich32-4.0b1/lib/libopa.so:000e7109 T PMPIX_Delete_error_code
[glci@pj03 f77]$ /home/glci/soft/mpich32-4.0b1/bin/mpif90 -show
gfortran -m32 -fallow-argument-mismatch -I/home/glci/soft/mpich32-4.0b1/include -I/home/glci/soft/mpich32-4.0b1/include -L/home/glci/soft/mpich32-4.0b1/lib -lmpifort -Wl,-rpath -Wl,/home/glci/soft/mpich32-4.0b1/lib -Wl,--enable-new-dtags -lmpi
[glci@pj03 f77]$ /home/glci/soft/mpich32-4.0b1/bin/mpif90 fpi.f 
[glci@pj03 f77]$ file a.out 
a.out: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, BuildID[sha1]=e76caf3cd7f4c7aec415ed6bd18368e3b07fd5c7, for GNU/Linux 3.2.0, not stripped
[glci@pj03 f77]$ ./a.out 
 Process            0  of            1  is alive
Enter the number of intervals: (0 quits)
0
[glci@pj03 f77]$ 
```

**Comment by hzhou** [comment]
> Hm - [I don't have my prior builds] - so did a rebuild - and can't reproduce this [with either 32bit or 64bit]. So don't know what went wrong with my previous build.

I suspect it was due to the interruption of configure due to https://github.com/pmodels/mpich/issues/5688#issue-1058900326, but not sure how it happened. We'll ignore this until it resurfaces :)

**Comment by lindsayad** [comment]
I am getting identical undefined references to what @balay experienced
```
(base) lindad@pop-os:~/mpich/installed/lib(main)$ nm libmpifort.so | grep Delete
                 U PMPI_Delete_error_class
                 U PMPI_Delete_error_code
                 U PMPI_Delete_error_string
```
Here is some more information
```
(base) lindad@pop-os:~/mpich/installed/lib(main)$ gfortran --version
GNU Fortran (Ubuntu 11.2.0-7ubuntu2) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(base) lindad@pop-os:~/mpich/installed/lib(main)$ mpiexec --version
HYDRA build details:
    Version:                                 4.1a1
    Release Date:                            unreleased development copy
    CC:                              gcc      
    Configure options:                       '--disable-option-checking' '--prefix=/home/lindad/mpich/installed' 'FCFLAGS=-fallow-argument-mismatch ' '--cache-file=/dev/null' '--srcdir=../../../../src/pm/hydra' 'CC=gcc' 'CFLAGS= ' 'LDFLAGS=' 'LIBS=' 'CPPFLAGS= '
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Demux engines available:                 poll select
```
I initially  had a configure that terminated due to not passing `-fallow-argument-mismatch` to `FCFLAGS`. However, given @balay 's experience I made sure to reconfigure from a fresh build directory, but the undefined references still persist

**Comment by raffenet** [comment]
@lindsayad thanks for the the report. What OS are you building on?

**Comment by raffenet** [comment]
Oh, duh. It says Ubuntu right there. We'll take a look...

**Comment by raffenet** [comment]
@lindsayad just to confirm, are you also building on 32-bit?

**Comment by lindsayad** [comment]
Sorry I should have made it clear... I am not. I'd be happy to open a new ticket. I am also happy to send the config.log although I'll need to regenerate it since I nuked that build directory when I chose to rebuild with 3.4.2

**Comment by raffenet** [comment]
> Sorry I should have made it clear... I am not. I'd be happy to open a new ticket. I am also happy to send the config.log although I'll need to regenerate it since I nuked that build directory when I chose to rebuild with 3.4.2

`config.log` would be helpful. Let's start with that and decide if a new ticket is warranted. Please also confirm the git hash or tarball you are building from.

**Comment by hzhou** [comment]
Ah, I think I know the culprit, `load_mpix_txt()` in `maint/local_python/mpi_api.py` failed to consider out-of-tree builds. Let me make a patch...
