### ISSUE TITLE
Build failure with "make check" on Mac

### ISSUE THREAD

**Issue by qkoziol** [pmodels/mpich#7520]
Getting a failure in ‘make check’ from a fresh pull:

```

> 
> Making check in hwloc
> /Applications/Xcode.app/Contents/Developer/usr/bin/make
> make[4]: Nothing to be done for `all’.
> make[3]: Nothing to be done for `check-am’.
> Making check in /Users/koziol/HPC/mpich/modules/json-c
> Making check in .
> Making check in tests
> /Applications/Xcode.app/Contents/Developer/usr/bin/make  test_util_file test_float test1 test2 test4 testReplaceExisting test_parse_int64 test_deep_copy test_null test_cast test_double_serializer test_parse test_locale test_charcase test_printbuf test_set_serializer test_compare test_set_value test_visit test_json_pointer test_int_add test1Formatted test2Formatted
>   CC       test_util_file.o
>   CCLD     test_util_file
>   CC       test_float.o
>   CCLD     test_float
>   CC       test1.o
>   CCLD     test1
>   CC       test2.o
>   CCLD     test2
>   CC       test4.o
>   CCLD     test4
>   CC       testReplaceExisting.o
>   CCLD     testReplaceExisting
>   CC       test_parse_int64.o
>   CCLD     test_parse_int64
>   CC       test_deep_copy.o
>   CCLD     test_deep_copy
>   CC       test_null.o
>   CCLD     test_null
>   CC       test_cast.o
>   CCLD     test_cast
>   CC       test_double_serializer.o
>   CCLD     test_double_serializer
>   CC       test_parse.o
>   CCLD     test_parse
>   CC       test_locale.o
>   CCLD     test_locale
>   CC       test_charcase.o
>   CCLD     test_charcase
>   CC       test_printbuf.o
>   CCLD     test_printbuf
>   CC       test_set_serializer.o
>   CCLD     test_set_serializer
>   CC       test_compare.o
>   CCLD     test_compare
>   CC       test_set_value.o
>   CCLD     test_set_value
>   CC       test_visit.o
>   CCLD     test_visit
>   CC       test_json_pointer.o
>   CCLD     test_json_pointer
>   CC       test_int_add.o
>   CCLD     test_int_add
>   CC       test1Formatted-test1.o
>   CC       test1Formatted-parse_flags.o
>   CCLD     test1Formatted
>   CC       test2Formatted-test2.o
>   CC       test2Formatted-parse_flags.o
>   CCLD     test2Formatted
> /Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
> PASS: test_util_file.test
> PASS: test_float.test
> PASS: test1.test
> PASS: test2.test
> PASS: test4.test
> PASS: testReplaceExisting.test
> PASS: test_parse_int64.test
> PASS: test_deep_copy.test
> PASS: test_null.test
> PASS: test_cast.test
> PASS: test_double_serializer.test
> PASS: test_parse.test
> PASS: test_locale.test
> PASS: test_charcase.test
> PASS: test_printbuf.test
> PASS: test_set_serializer.test
> PASS: test_compare.test
> PASS: test_set_value.test
> PASS: test_visit.test
> PASS: test_json_pointer.test
> PASS: test_int_add.test
> ============================================================================
> Testsuite summary for json-c 0.13.99
> ============================================================================
> # TOTAL: 21
> # PASS:  21
> # SKIP:  0
> # XFAIL: 0
> # FAIL:  0
> # XPASS: 0
> # ERROR: 0
> ============================================================================
> Making check in src/mpi/datatype/typerep/yaksa
> Making check in src/pmi
> make[3]: Nothing to be done for `check-am’.
> Making check in src/mpi/romio
> Making check in .
> Making check in test
> make  simple perf async coll_test coll_perf misc file_info excl large_array atomicity noncontig i_noncontig noncontig_coll split_coll shared_fp large_file psimple error status noncontig_coll2 aggregation1 aggregation2 async-multiple ordered_fp hindexed external32 types_with_zeros darray_read syshints fstype_prefix
>   CC       simple.o
>   CCLD     simple
>   CC       perf.o
>   CCLD     perf
>   CC       async.o
> async.c:35:5: error: unknown type name ‘MPIO_Request’; did you mean ‘MPI_Request’?
>    35 |     MPIO_Request request;
>       |     ^~~~~~~~~~~~
>       |     MPI_Request
> /Users/koziol/HPC/install/include/mpi.h:327:13: note: ‘MPI_Request’ declared here
>   327 | typedef int MPI_Request;
>       |             ^
> async.c:92:5: error: call to undeclared function ‘MPIO_Wait’; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
>    92 |     MPIO_Wait(&request, &status);
>       |     ^
> async.c:92:5: note: did you mean ‘MPI_Wait’?
> /Users/koziol/HPC/install/include/mpi_proto.h:687:5: note: ‘MPI_Wait’ declared here
>   687 | int MPI_Wait(MPI_Request *request, MPI_Status *status) MPICH_API_PUBLIC;
>       |     ^
> 2 errors generated.
> make[4]: *** [async.o] Error 1
> make[3]: *** [check-am] Error 2
> make[2]: *** [check-recursive] Error 1
> make[1]: *** [check-recursive] Error 1
> make: *** [check] Error 2
> 

```
On a Mac, with this configure:   ./configure --prefix=/Users/koziol/HPC/install --enable-f08

**Comment by raffenet** [comment]
This broke in 1311107d79ab4e9bf8f3af1376e0178e0b08bc90 when we stopped including `mpio.h` in `mpi.h`. MPICH always defines the I/O interfaces now so perhaps these tests should just deal in standard MPI objects and functions? That or we explicitly include `mpio.h` the offending tests.

**Comment by qkoziol** [comment]
Thanks!  Works for me now.
