### ISSUE TITLE
Duplicate file in C/Fortran MPICH libraries

### ISSUE THREAD

**Issue by eschnett** [pmodels/mpich#6814]
I am building MPICH 4.1.2. statically (but with `-fPIC`) on Apple. I find that both libraries `libpmpi.a` and `libmpifort.a` contain the object file `setbotf.o`. I later link both libraries into a shared library I create, and this fails because of duplicate symbols.

Postprocessing the MPICH libraries via
```sh
# Delete duplicate file
if ar t ${prefix}/lib/mpich/lib/libpmpi.a | grep -q setbotf.o; then
    ar d ${prefix}/lib/mpich/lib/libmpifort.a setbotf.o
fi
```
resolves the issue.

**Comment by hzhou** [comment]
Indeed. Will you be able to test #6815?

**Comment by eschnett** [comment]
@hzhou I am trying in the CI for https://github.com/JuliaPackaging/Yggdrasil/pull/7727. So far I'm encountering unrelated problems, e.g. building from a git checkout instead of a release tarball.

**Comment by eschnett** [comment]
It seems the duplicate files are gone, although I could not build successfully with this version of MPICH. (Things worked fine with the 4.1.2 release when removing the duplicate files manually.) I don't know what is wrong, I see cmake errors in Github's CI complaining that MPI is not available.

**Comment by hzhou** [comment]
@eschnett I believe I finally got it right in #6815. Could you test it again?
