### ISSUE TITLE
build: failure with icc 13.0

### ISSUE THREAD

**Issue by mpichbot** [pmodels/mpich#1659]
**Originally by _balaji_ on 2012-07-18 23:04:59 -0500**

---

MPICH2 fails to build with the Intel 13.0 compiler (I tried it on the MCS knight machine).  The make step mostly finishes without errors, but the generated library seems to be missing some symbols, so cpi fails to compile.

```
% ./configure --disable-cxx --disable-f77 --disable-fc --disable-romio --disable-mpe --prefix=`pwd`/install CC=icc

% icc --version
icc (ICC) 13.0.0 20120530
Copyright (C) 1985-2012 Intel Corporation.  All rights reserved.
```

Failed part of the output:

```
make[2]: Entering directory `/home/balaji/software/mpich2/trunk/build/examples'
  CC     cpi.o
  CCLD   cpi
cpi.o: In function `main':
../../trunk/examples/cpi.c:(.text+0x5e): undefined reference to `MPI_Init'
../../trunk/examples/cpi.c:(.text+0x70): undefined reference to `MPI_Comm_size'
../../trunk/examples/cpi.c:(.text+0x82): undefined reference to `MPI_Comm_rank'
../../trunk/examples/cpi.c:(.text+0x93): undefined reference to `MPI_Get_processor_name'
../../trunk/examples/cpi.c:(.text+0xde): undefined reference to `MPI_Wtime'
../../trunk/examples/cpi.c:(.text+0x106): undefined reference to `MPI_Bcast'
../../trunk/examples/cpi.c:(.text+0x33a): undefined reference to `MPI_Reduce'
../../trunk/examples/cpi.c:(.text+0x34d): undefined reference to `MPI_Wtime'
../../trunk/examples/cpi.c:(.text+0x3b2): undefined reference to `MPI_Finalize'
make[2]: *** [cpi] Error 1
make[2]: Leaving directory `/home/balaji/software/mpich2/trunk/build/examples'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/balaji/software/mpich2/trunk/build'
make: *** [all] Error 2
```

Some more useful output with this build (notice the bunch of zeroes, and missing MPI_Init):

```
% nm install/lib/libmpich.a | grep MPI_Init
0000000000000000 T PMPI_Init
0000000000000000 T PMPI_Initialized
00000000000000d0 T PMPI_Init_thread
```

With a correct build on a different machine, here's the output:

```
                 U PMPI_Initialized
                 U PMPI_Init
                 U PMPI_Init_thread
00000000000013e0 W MPI_Init
00000000000013e0 T PMPI_Init
00000000000013e0 W MPI_Initialized
00000000000013e0 T PMPI_Initialized
0000000000001c80 W MPI_Init_thread
0000000000001c80 T PMPI_Init_thread
```

**Comment by jeffhammond** [comment]
This issue should be closed.
