### PR TITLE
qmpi: chop MPICH_API_PUBLIC from the definition

### LINKED ISSUE #5829: qmpi: failed to build in mpich-4.0
From discuss mailinglist:

> [quote]
Hi Mpich team,

I see the following issue with the latest 4.0 release of MPICH while adding QMPI support at configure time?

make[2]: Entering directory `/scratch1/05231/aruhela/libs/mpich/tar-mpich-4.0'
  CC       src/binding/c/attr/lib_libmpi_la-attr_delete.lo
src/binding/c/attr/attr_delete.c(63): error: attributes are not permitted in a function definition
  int QMPI_Attr_delete(QMPI_Context context, int tool_id, MPI_Comm comm, int keyval) MPICH_API_PUBLIC
                                                                                                                                                                 ^

compilation aborted for src/binding/c/attr/attr_delete.c (code 2)
make[2]: *** [src/binding/c/attr/lib_libmpi_la-attr_delete.lo] Error 1

Any suggestions to resolve the build error?

Amit Ruhela, Ph.D. 
HPC Software Tools Group 
Texas Advanced Computing Center 
The University of Texas at Austin

### PR DESCRIPTION
**Pull request by hzhou**
## Pull Request Description
MPICH_API_PUBLIC is accidentally leaked into definitions, which isn't
allowed.

Fixes #5829

[skip warnings]

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [x] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by hzhou** [comment]
test:mpich/ch4/ofi

**Comment by hzhou** [comment]
Fix confirmed by user.

**Comment by hzhou** [comment]
Added a better fix. Rather than replace the `MPICH_API_PUBLIC` away, do not generate it in the first place. Will squash the commits before after review.
