### PR TITLE
hydra: isolate spawn rankmap from parent job occupancy

### LINKED ISSUE #7794: test/spawn: Spawn multiple errors when running on > 1 nodes
I've been doing some testing on a 2- node setup and noticed that some MPI_Comm_spawn_multiple tests would encounter errors like this:
```console
$ mpiexec -n 1 ./spawnmultf
 Found arg -p                                                                               but expected a
 Found arg 27                                                                               but expected b=c
 Found arg -echo                                                                            but expected d e
 Too few arguments to spawned command
 Found arg a                                                                                but expected -p
 Found arg b=c                                                                              but expected 27
 Found arg d e                                                                              but expected -echo
 Wrong number of arguments (           5 )
  Found            8  errors
```
Initially I thought it was an off-by-one error with the Fortran bindings, but with some (AI) assistance the problem actually looks to be the way Hydra was mapping executables and arguments. Will post a PR with a proposed fix, but am open to feedback.

### PR DESCRIPTION
**Pull request by raffenet**
## Pull Request Description

HYDU_gen_rankmap uses node->active_processes in its filler round to bias placement when ranks exceed cores. When called for a spawned process group, residual active_processes from the parent job skews the rank-to-exec mapping produced by HYDU_create_proxy_list, reordering MPI_Comm_spawn_multiple commands relative to their ranks and MPI_APPNUM values. The symptom manifested identically in C, f77, and f08 spawn_multiple tests as apparently lost or shifted argv entries on spawned children.

Generate the spawn rankmap from a duplicated node list with active_processes zeroed so spawn ordering depends only on command order. The real node list is still used for proxy creation so proxy reuse introduced in 4ae7868382 is preserved. Fixes pmodels/mpich#7794.

## Author Checklist
* [x] **Provide Description** 
      Particularly focus on _why_, not _what_. Reference background, issues, test failures, xfail entries, etc.
* [x] **Commits Follow Good Practice**
      Commits are self-contained and do not do two things at once. 
      Commit message is of the form: `module: short description` 
      Commit message explains what's in the commit.
* [ ] **Passes All Tests**
      Whitespace checker. Warnings test. Additional tests via comments.
* [x] **Contribution Agreement**
      For non-Argonne authors, check [contribution agreement](http://www.mpich.org/documentation/contributor-docs/). 
      If necessary, request an explicit comment from your companies PR approval manager.

### CODE REVIEW

**Comment by raffenet** [comment]
While this fixes the immediate test issue I'm seeing, it occurs to me that it kind of bypasses the problem which (I think) is accurate executable/argument-to-node mapping for spawned processes in the presence of existing filler processes? I'll think more about a proper fix, but welcome any comments or suggestions.

**Comment by hzhou** [comment]
> Generate the spawn rankmap from a duplicated node list with active_processes zeroed so spawn ordering depends only on command order.

To respect `active_processes` when spawning processes is a feature, so that for applications that repeatedly using spawn to expand jobs can utilize all nodes equally. The issue is the proxy are not assigning ranks correctly. I'll troubleshoot the issue.

**Comment by hzhou** [comment]
@raffenet Try test #7798
