### ISSUE TITLE
build: mpich-3.3 static link error on OSX

### ISSUE THREAD

**Issue by balay** [pmodels/mpich#3449]
I get the following link error with static build of mpich-3.3 on osx.

```
balay@ipro^~/junk $ ~/petsc/arch-darwin-c-debug/bin/mpicc cpi.c
Undefined symbols for architecture x86_64:
  "_clGetDeviceIDs", referenced from:
      _hwloc_opencl_discover in libpmpi.a(topology-opencl.o)
  "_clGetDeviceInfo", referenced from:
      _hwloc_opencl_discover in libpmpi.a(topology-opencl.o)
  "_clGetPlatformIDs", referenced from:
      _hwloc_opencl_discover in libpmpi.a(topology-opencl.o)
  "_clGetPlatformInfo", referenced from:
      _hwloc_opencl_discover in libpmpi.a(topology-opencl.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

attaching config.log for this build
[config.log.txt](https://github.com/pmodels/mpich/files/2620615/config.log.txt)

**Comment by pavanbalaji** [comment]
This seems to be coming from `hwloc`.  @KavithaTipturMadhu can you look into it?

**Comment by KavithaTipturMadhu** [comment]
I am looking into this, will update it once I have more info.

**Comment by KavithaTipturMadhu** [comment]
I built the static library with the same config flags and static mpi lib on osx. cpi seems to run just fine. Can I get access to your build or details of compiler and linker versions?

**Comment by balay** [comment]
Its latest OSX with latest Xcode. We use gfortran from brew.

```
balay@ipro^~ $ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391
balay@ipro^~ $ xcodebuild -version
Xcode 10.1
Build version 10B61
balay@ipro^~ $ clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
balay@ipro^~ $ 

```
Note: the shared build is linked in with OpenCL - so presumably a static build presumably needs an explicit OpenCL link in the mpi wrapper.

```
balay@ipro^/Users/petsc/petsc.next-tmp-3/arch-osx-10.6-cxx-cmplx-pkgs-dbg/lib((f8627fd784...)) $ otool -L libpmpi.dylib 
libpmpi.dylib:
	/Users/petsc/petsc.next-tmp-3/arch-osx-10.6-cxx-cmplx-pkgs-dbg/lib/libpmpi.12.dylib (compatibility version 14.0.0, current version 14.6.0)
	/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/gcc/lib/gcc/8/libgfortran.5.dylib (compatibility version 6.0.0, current version 6.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
	/usr/local/lib/gcc/8/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/gcc/lib/gcc/8/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)

```

**Comment by balay** [comment]
```
balay@ipro^~/petsc/arch-darwin-c-debug/externalpackages/mpich-3.3/src/hwloc((f8627fd784...)) $ ./configure --help |grep opencl
  --disable-opencl        Disable the OpenCL device discovery
```
I guess I should use this option to workaround this issue.

**Comment by balay** [comment]
Now I get duplicate symbol errors

```
balay@ipro^~/petsc/src/ksp/ksp/examples/tutorials((f8627fd784...)) $ /Users/balay/petsc/arch-darwin-c-debug/bin/mpicc -g3  -o ex2 ex2.o  -L/Users/balay/petsc/arch-darwin-c-debug/lib  -L/usr/local/Cellar/gcc/8.2.0/lib/gcc/8 -lpetsc -llapack -lblas -lgfortran
duplicate symbol _MPIR_Op_create_impl in:
    /Users/balay/petsc/arch-darwin-c-debug/lib/libmpi.a(lib_libmpi_la-op_create.o)
    /Users/balay/petsc/arch-darwin-c-debug/lib/libpmpi.a(lib_libpmpi_la-op_create.o)
duplicate symbol _MPIR_Op_free_impl in:
    /Users/balay/petsc/arch-darwin-c-debug/lib/libmpi.a(lib_libmpi_la-op_free.o)
    /Users/balay/petsc/arch-darwin-c-debug/lib/libpmpi.a(lib_libpmpi_la-op_free.o)
duplicate symbol _MPIR_Waitany_impl in:
    /Users/balay/petsc/arch-darwin-c-debug/lib/libmpi.a(lib_libmpi_la-waitany.o)
    /Users/balay/petsc/arch-darwin-c-debug/lib/libpmpi.a(lib_libpmpi_la-waitany.o)
ld: 3 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
balay@ipro^~/petsc/src/ksp/ksp/examples/tutorials((f8627fd784...)) $ nm -A /Users/balay/petsc/arch-darwin-c-debug/lib/lib*mpi.a |grep _MPIR_Op_create_impl
/Users/balay/petsc/arch-darwin-c-debug/lib/libmpi.a:lib_libmpi_la-op_create.o: 0000000000000000 T _MPIR_Op_create_impl
/Users/balay/petsc/arch-darwin-c-debug/lib/libpmpi.a:lib_libpmpi_la-op_create.o: 00000000000001e0 T _MPIR_Op_create_impl
balay@ipro^~/petsc/src/ksp/ksp/examples/tutorials((f8627fd784...)) $ 

```

**Comment by raffenet** [comment]
At least waitany was broken in 7e047915e3ac8365082beeb6b9ded8333481bf48. @KavithaTipturMadhu I have a fix I will push. I'm sure we'll need something similar for the duplicate op symbols.

**Comment by balay** [comment]
@raffenet @KavithaTipturMadhu , Thanks for the fixes. My builds go past this link error now.

**Comment by raffenet** [comment]
Great. Thanks for confirming.

**Comment by balay** [comment]
Yes the primary issue with OpenCL still exists. [I'm just working arround it].

**Comment by balay** [comment]
```
balay@ipro^~ $ which ar
/usr/bin/ar
```

I haven't tried a build in a while - but I didn't have a bad 'ar' in PATH
