### ISSUE TITLE
Duplicate symbols in C/Fortran MPICH libraries

### ISSUE THREAD

**Issue by hansec** [pmodels/mpich#7272]
Similar to #6814, I am building MPICH 4.2.3. statically (with `-fPIC`) on macOS. I find that both libraries `libmpi.a`/`libpmpi.a` and `libmpifort.a` contain the objects for the F08<->C status conversion functions (`MPI_Status_c2f08`, `MPI_Status_f08c`, `PMPI_Status_c2f08`, `PMPI_Status_f08c`). I later try to link all three libraries into a shared library, which fails because of duplicate symbols. This process works on 4.2.2.

The objects are defined in `mpi_f08_types.o` in `libmpifort.a` and in `lib_libpmpi_la-c_binding.o`/`lib_libmpi_la-c_binding.o` in `libpmpi.a`/`libmpi.a`.

I assume a fix similar to #6815 can fix this?
