### PR TITLE
GPU Support query

### PR DESCRIPTION
**Pull request by pavanbalaji**
## Pull Request Description

This PR provides new MPIX_ functions for users to query for GPU support.  It adds one function `MPIX_Query_cuda_support` that is similar to what Open MPI and MVAPICH provide, and one function `MPIX_GPU_query_support` that is a bit more generic to allow for multiple GPUs, but not by too much.

Fixes https://github.com/pmodels/mpich/issues/4716

## Author Checklist
* [x] Reference appropriate issues (with "Fixes" or "See" as appropriate)
* [x] Remove xfail from the test suite when fixing a test
* [x] Commits are self-contained and do not do two things at once
* [x] Commit message is of the form: `module: short description` and follows [good practice](https://chris.beams.io/posts/git-commit/)
* [x] Passes whitespace checkers
* [x] Passes warning tests
* [ ] Passes all tests
* [x] Add comments such that someone without knowledge of the code could understand
* [x] You or your company has a signed contributor's agreement on file with Argonne
* [x] For non-Argonne authors, request an explicit comment from your companies PR approval manager

### CODE REVIEW

**Comment by pavanbalaji** [comment]
test:mpich/warnings/gpu
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by pavanbalaji** [comment]
> My only nitpick is that the MPL part could be split from the MPIX additions, but otherwise this is fine.

Fixed.  Also fixed a compilation error that clang caught.  Retesting.

test:mpich/warnings/gpu
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by pavanbalaji** [comment]
test:mpich/warnings/gpu
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by pavanbalaji** [comment]
test:mpich/warnings/gpu
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by pavanbalaji** [comment]
test:mpich/warnings/gpu
test:mpich/ch3/most
test:mpich/ch4/most

**Comment by pavanbalaji** [comment]
The failing tests seem to have been introduced by https://github.com/pmodels/mpich/pull/4738 and are unrelated to this PR.

**Comment by leofang** [comment]
Dear @pavanbalaji, thank you very much for addressing my request! I have a few questions given my ignorance on the MPICH internal:
- What does the ZE support mean?
- Do the two new query APIs need to be called after `MPI_Init()`?
- Does MPICH have the concept of "CUDA support is built but disabled at runtime"? If so, how do I know if it's the case?

Thanks again!
